[package]
name = "template-manager"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
